[[methods]]
= Operation

The client currently has multiple methods to generate documents, retrieve metadata of the created documents, and fetch the generated document itself.

During document generation, some methods return the generated document.
The generated documents can be fetched in GZIP compressed format if needed with the client's `setResponseContentGzipped(boolean)` method:

[source,java]
----
public GeneratedDocumentDto postDocumentGenerateEntityBody(Collection<TemplateType> templates, Collection<ParameterType> parameters) throws BaseException;

public GeneratedDocumentDto postDocumentGenerateEntityBody(Collection<TemplateType> templates, ParametersDataType parametersData) throws BaseException;

public GeneratedDocumentDto postDocumentGenerateEntityBody(Collection<TemplateType> templates) throws BaseException;

public GeneratedDocumentDto postDocumentGenerateMultipart(InputStream template, Collection<ParameterType> parameters) throws BaseException;

public GeneratedDocumentDto postDocumentGenerateMultipart(InputStream template, ParametersDataType parametersData) throws BaseException;

public GeneratedDocumentDto postDocumentGenerateMultipart(InputStream template) throws BaseException;

public GeneratedDocumentDto postDatabaseStoredTemplateDocumentGenerate(String templateName, OffsetDateTime templateValidity, Collection<ParameterType> parameters) throws BaseException;

public GeneratedDocumentDto postDatabaseStoredTemplateDocumentGenerate(String templateName, OffsetDateTime templateValidity, ParametersDataType parametersData) throws BaseException;
----

It is important to note that `ParametersDataType` type parameters can be created manually, but a `ParametersDataBuilder` helper class is provided to configure the desired settings using a fluent API. This was required by the SAXON template engine, as additional parameters are necessary for generating XSLT templates, without which documents cannot be generated. The desired configuration can be easily extracted from the builder for the SAXON engine by calling the `getSaxonParameters(byte[], byte[], boolean)` method, where the FOP configuration content, the XML dataset, and the compression status of the XML can be specified, or through overloaded methods, just the content of the XML file.

[source,java]
----
GeneratedDocumentDto resp = client.postDatabaseStoredTemplateDocumentGenerate(
        TemplateLanguageType.HU, <1>
        ParametersDataBuilder.getSaxonParameters(
                FileUtil.readFileFromResource(DocumentServiceTestConstant.XSLT_TEMPLATE_PARAMS).getBytes(StandardCharsets.UTF_8))); <2>
----
<1> The language of the template
<2> The content of the XML dataset (uncompressed in this case)

These methods return a `GeneratedDocumentDTO` upon a successful call, which contains the generated filename, the generated object as a stream, and the HTTP status code.

Parameters must include the list of templates and the parameters if the templates contain variables that need to be replaced with values, such as in the case of the HANDLEBARS template engine. The parameters can be key-value pairs or a JSON object that essentially contains these key-value pairs.

The methods differ in the way the template for document generation is provided.
In the `postDocumentGenerateEntityBody()` methods, the structure used as a template is sent in the request body. In the `postDocumentGenerateMultipart()` methods, the template is provided as a form parameter, InputStream. In the `postDatabaseStoredTemplateDocumentGenerate()` methods, only the template name needs to be provided, as the endpoint handles it according to the specified storage method.

Additionally, methods are available for generating documents where only the metadata of the created document is returned instead of the document itself:

[source,java]
----
public DocumentMetadataResponse postDocumentGenerateEntityBodyMetadata(Collection<TemplateType> templates, Collection<ParameterType> parameters) throws BaseException;

public DocumentMetadataResponse postDocumentGenerateEntityBodyMetadata(Collection<TemplateType> templates, ParametersDataType parametersData) throws BaseException;

public DocumentMetadataResponse postDocumentGenerateEntityBodyMetadata(Collection<TemplateType> templates) throws BaseException;

public DocumentMetadataResponse postDocumentGenerateMultipartMetadata(InputStream template, Collection<ParameterType> parameters) throws BaseException;

public DocumentMetadataResponse postDocumentGenerateMultipartMetadata(InputStream template, ParametersDataType parametersData) throws BaseException;

public DocumentMetadataResponse postDocumentGenerateMultipartMetadata(InputStream template) throws BaseException;

public DocumentMetadataResponse postDatabaseStoredTemplateDocumentGenerateMetadata(String templateName, OffsetDateTime templateValidity, Collection<ParameterType> parameters) throws BaseException;

public DocumentMetadataResponse postDatabaseStoredTemplateDocumentGenerateMetadata(String templateName, OffsetDateTime templateValidity, ParametersDataType parametersData) throws BaseException;

public DocumentMetadataResponse postStoredTemplateDocumentGenerateMetadata(String templateName, OffsetDateTime templateValidity, TemplateStorageMethodType templateStorageMethodType, Collection<ParameterType> parameters, ParametersDataType parametersData) throws BaseException;
----

These methods return a `DocumentMetadataResponse` upon a successful call, which includes the unique identifier of the document, filename, storage method, format, and status.

Similarly, the client calls are distinguished in the same way by how the template is provided.

To view already generated files, there is an option to query the metadata of the documents:

[source,java]
----
public DocumentMetadataQueryResponse postDocumentMetadataQuery(DocumentMetadataQueryParamsType queryParams) throws BaseException;

public DocumentMetadataQueryResponse postDocumentMetadataQuery(DocumentMetadataQueryRequest queryRequest) throws BaseException;
----

The query returns a `DocumentMetadataQueryResponse` upon a successful call, which contains the metadata of documents matching the specified parameters, as well as pagination data: total number of items, total number of pages, page number, and the number of items returned in the query.

Filtering conditions can include the document name, format, storage method, template identifier from which the document was generated, the identifier of the document's storage, and the status of the document.

It is also possible to query a previously generated document:

[source,java]
----
public GeneratedDocumentDto getDocumentContent(String documentId) throws BaseException;
----

The response returns the generated document as a stream, the filename, and the HTTP status code upon a successful call.

The unique identifier of the document must be provided as a parameter.

The client also offers additional configuration options that can influence the generation process:

[source,java]
----
setGeneratorEngineType()
----

[source,java]
----
setTemplateEngineType()
----

[source,java]
----
setResponseFormat()
----

[source,java]
----
setDocumentStorageMethodType()
----

[source,java]
----
setDigitalSigningType()
----

[source,java]
----
setResponseContentGzipped()
----

The `setGeneratorEngineType()` allows setting the engine used for output generation, which currently can be:

* `PDF_BOX` -- uses [Apache PdfBox](https://pdfbox.apache.org/)
* `SAXON` -- uses [Saxon HE](https://github.com/Saxonica/Saxon-HE/)
* `NONE`

The `setTemplateEngineType()` allows setting the template 'type', which currently can be:

* `HANDLEBARS` -- uses [Handlebars](https://handlebarsjs.com/)
* `NONE`

The `setResponseFormat()` allows setting the response format:

* `PDF`
* `STRING`

The `setDocumentStorageMethodType()` allows setting the document storage method:

* `NONE`
* `DATABASE`

The `setDigitalSigningType(digitalSigningType)` allows controlling whether the generated PDF document should have a digital signature. The `digitalSigning` expects three additional parameters:

* `signatureName` - the name of the signature (optional)
* `signatureReason` - the reason for signing (optional)
* `keyAlias` - the identifier of the key in the keystore, used to identify the signing key (optional, but recommended as it defaults to searching for the `test` key)

If no settings are specified, the default values are `PDF_BOX` + `HANDLEBARS` + `PDF` + `NONE` without a digital signature.

The `setResponseContentGzipped(boolean)` method allows controlling whether the generated document should be returned in GZIP compressed format.

The `postDocumentGenerateEntityBody()` methods call the following REST endpoint in the module:

[source,text]
----
POST /internal/dookug/document/generate/inline
----

The client sends:

* `ContextType`
* the received `TemplateType` list
* the received `ParameterType` list
* the `GeneratorSetup` object, which can be controlled by the client's `set` methods.

If the request is correct, the generated object is returned.

[NOTE]
====
For Multipart and StoredTemplate clients, the process is the same, differing only in the REST API calls.
====

The `postDocumentMetadataQuery()` methods call the following REST endpoint in the module:

[source,text]
----
POST /internal/dookug/document/storedTemplate/metadata/query
----

The client sends:

* `ContextType`
* the received filtering conditions
* pagination parameters
* sorting settings

If the request is correct, the metadata of the documents matching the specified parameters is returned.

Example of client usage:

[source,java]
----
 @Inject
 private DookugClient dookugClient;
 ...
 //template object
 TemplateType template = new TemplateType().withTemplateName("main").withTemplateContent("DookuG client simple test with parameters first: [{{first}}], second: [{{second}}]".getBytes(StandardCharsets.UTF_8));

 //parameters
 ParameterType parameter1 = new ParameterType().withKey("first").withValue("első");
 ParameterType parameter2 = new ParameterType().withKey("second").withValue("í189öüóőúűáé-.,<>#&@{};*¤ß$");
 ...
 dookugClient.setResponseFormatType(ResponseFormatType.STRING);
 dookugClient.setGeneratorEngineType(GeneratorEngineType.NONE);
 GeneratedDocumentDto response = dookugClient.postDocumentGenerateEntityBody(List.of(template), List.of(parameter1,parameter2));
----

Or similarly, generating a document but with a PDF document format, multipart input, and returning the metadata:

[source,java]
----
 @Inject
 private DookugClient dookugMultipartClient;
 ...
 //template as byte array
 byte[] template = "DookuG client simple test with parameters first: [{{first}}], second: [{{second}}]".getBytes(StandardCharsets.UTF_8);

 //parameters
 ParameterType parameter1 = new ParameterType().withKey("first").withValue("első");
 ParameterType parameter2 = new ParameterType().withKey("second").withValue("í189öüóőúűáé-.,<>#&@{};*¤ß$");
 ...
 dookugMultipartClient.setResponseFormatType(ResponseFormatType.PDF); // this is the default
 dookugMultipartClient.setGeneratorEngineType(GeneratorEngineType.PDF_BOX); // this is the default
 dookugMultipartClient.setTemplateEngineType(GeneratorEngineType.HANDLEBARS); // this is the default
 DocumentMetadataResponse response = dookugMultipartClient.postDocumentGenerateMultipartMetadata(new ByteArrayInputStream(template), List.of(parameter1, parameter2));
----

== Using Saxon-HE Engine in the Client

To use the Saxon-HE engine in the client, an XSLT template is required for generating a PDF file from an XML. In this case, only PDF can be the output format. You also need to provide a `fop-config.xml` file in the request, which helps regulate the use of fonts, for example.

[source,xml]
----
<?xml version="1.0" encoding="UTF-8"?>
<fop version="1.0">
    <renderers>
        <renderer mime="application/pdf">
            <fonts>
                <!-- TTF fonts -->
                <font kerning="yes" embed-url="/home/icellmobilsoft/fonts/Roboto/Roboto-Regular.ttf">
                    <font-triplet name="Roboto" style="normal" weight="normal" />
                </font>
                <font kerning="yes" embed-url="/home/icellmobilsoft/fonts/Roboto/Roboto-Bold.ttf">
                    <font-triplet name="Roboto" style="normal" weight="bold" />
                </font>
            </fonts>
        </renderer>
    </renderers>
</fop>
----

Handlebars can also be used with SAXON, where you can substitute the usual `{{VARIABLE}}` variables with desired text parts, as well as create nested templates (this is mainly used for that).

The major change from other engines is that you need to specify the `XML` as a data source in the `generatorSetup` in the SAXON case, in addition to other fields:

- XML: as data source
- XSLT: as template
- fopConfig: transformer configuration
