# config file version
apiVersion: 1

# List of contact points to import or update
contactPoints:
  # <int> organization ID, default = 1
  - orgId: 1
    # <string, required> name of the contact point
    name: cp_chat
    receivers:
      # <string, required> unique identifier for the receiver. Should not exceed 40 symbols. Only letters, numbers, - (hyphen), and _ (underscore) allowed.
      - uid: second_uid
        # <string, required> type of the receiver
        type: googlechat
        # <bool, optional> Disable the additional [Incident Resolved] follow-up alert, default = false
        disableResolveMessage: false
        # <object, required> settings for the specific receiver type
        # replace the WEBHOOK_URL with your webhook, example: https://chat.googleapis.com/v1/spaces/yYhAMgAAAAE/messages?key=...
        settings:
          url: WEBHOOK_URL