apiVersion: 1
groups:
  - orgId: 1
    name: testgroup
    folder: testdir
    interval: 2m
    rules:
      - uid: cdpdbl9upnp4wc
        title: testrule
        condition: C
        data:
          - refId: A
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: fixeduid
            model:
              editorMode: code
              expr: vector(1)
              instant: true
              intervalMs: 1000
              legendFormat: __auto
              maxDataPoints: 43200
              range: false
              refId: A
          - refId: C
            relativeTimeRange:
              from: 600
              to: 0
            datasourceUid: __expr__
            model:
              conditions:
                - evaluator:
                    params:
                      - 0
                    type: gt
                  operator:
                    type: and
                  query:
                    params:
                      - C
                  reducer:
                    params: []
                    type: last
                  type: query
              datasource:
                type: __expr__
                uid: __expr__
              expression: A
              intervalMs: 1000
              maxDataPoints: 43200
              refId: C
              type: threshold
        noDataState: NoData
        execErrState: Error
        for: 2m
        annotations: {}
        labels: {}
        isPaused: false
        notification_settings:
          receiver: cp_email