# config file version
apiVersion: 1

# List of templates to import or update
templates:
  # <int> organization ID, default = 1
  - orgId: 1
    # <string, required> name of the template, must be unique
    name: alerts.message
    # <string, required> content of the template
    template: |
      {{ define "alerts.message" -}}
      {{ if .Alerts.Firing -}}
      {{ len .Alerts.Firing }} firing alert(s)
      {{ template "alerts.summarize_labels_and_values" .Alerts.Firing }}
      {{- end }}
      {{- if .Alerts.Resolved -}}
      {{ len .Alerts.Resolved }} resolved alert(s)
      {{ template "alerts.summarize_labels_and_values" .Alerts.Resolved }}
      {{- end }}
      {{- end }}
      
      {{ define "alerts.summarize_labels_and_values" -}}
      {{ range . -}}
      - {{ range $k, $v := .Labels }}{{ $k }}={{ $v }} {{ end }}{{ range $k, $v := .Values }}{{ $k }}={{ $v }} {{ end }}
      {{ end }}
      {{ end }}