:toc: left
:toclevels: 4
:sectnums:
:sectnumlevels: 4
:source-highlighter: rouge
:rouge-style: thankful_eyes
:icons: font

= DookuG backend

== About the project

Brief overview:

* Document generation module based on templates, which
- can handle templates in different formats and inject parameter lists into them, then generate the finished document.
- The module is designed to generate output documents (PDF, XLSX, HTML, TXT, ...) from various template formats with identifiers (TXT, HTML, object, JRXML, ...) by inserting the received parameter(s) into the received template.
- The solution is based on a microservice architecture.

== Technologies

.Service (jar, war)
- Java 17+
- Java EE 10
- Wildfly 27.0.1.Final

== Services

* dookug-document-service - contents:
** Generating document with stored template data
** Generating document from request data
** Query content of generated document
** Generating document from request and stored template data

== Development Environment

For setting up a development environment, local Docker Compose files are available in the `etc/docker-compose` directory.

=== Running the Full Environment

With a single command, you can launch all the necessary and optional containers, including the database with Liquibase scripts, the application server, Graylog along with its dependencies, and the observability tools.

.Start all containers (_click to expand_)
[%collapsible]
========
Currently, Oracle XE and Postgres database profiles are available. Command for running full environment from project root directory:

.Start all containers (Oracle)
[source,shell]
docker compose -f ./etc/docker-compose/docker-compose.local.all.yml --profile oracle up

.Start all containers (PostgreSQL)
[source,shell]
docker compose -f ./etc/docker-compose/docker-compose.local.all.yml --profile pg up

Once all containers are up and running, deploy the application as described in the <<war-deploy, Deploying the Application>> section.

========

=== Running Components Separately

If needed, you can start individual components separately.

.Running the Database (_click to expand_)
[%collapsible]
========
Currently, Oracle XE and PostgreSQL databases are supported. Use one of the following commands to start the database along with Liquibase migrations from the project root directory:

.Start Oracle
[source,shell]
docker compose -f ./etc/docker-compose/docker-compose.local.oracle.yml up --build --force-recreate

.Start PostgreSQL
[source,shell]
docker compose -f ./etc/docker-compose/docker-compose.local.postgredb.yml up --build --force-recreate

========

.Running the WildFly Application Server (_click to expand_)
[%collapsible]
========

The application server requires the corresponding database. Use the respective command based on your chosen database:

.Start WildFly with Oracle
[source,shell]
docker compose -f ./etc/docker-compose/docker-compose.local.dookug-document-service.oracle.yml up --build --force-recreate

.Start WildFly with PostgreSQL
[source,shell]
docker compose -f ./etc/docker-compose/docker-compose.local.dookug-document-service.postgresql.yml up --build --force-recreate

========

.Deploying the Application (_click to expand_)
[%collapsible]
========
[[war-deploy]]

.Compile the application:
[source,shell]
mvn clean install

.Deploy the `.war` file to the application server
[source,shell]
mvn -f dookug-document/dookug-document-service/pom.xml exec:exec -P deploy

========

.Observability (optional, _click to expand_)
[%collapsible]
========

To enable observability tools, run:

.Prometheus, Grafana, Jaeger:
[source,shell]
docker compose -f ./etc/docker-compose/docker-compose.local.observability.yml up --build --force-recreate
========

== Testing

The developer tests are located in the `dookug-testsuite` Maven module.
The tests use the https://github.com/i-Cell-Mobilsoft-Open-Source/roaster[Roaster] project and execute fully autonomous REST external calls to the deployed application.
They can be run either directly from the developer UI using the JUnit plugin or via Maven by activating the appropriate profile, for example:

[source,bash]
----
mvn verify -Dprofile <1>
mvn verify -Dprofile=sandbox,local <2>
----
<1> default parameters
<2> Selected profiles from the `etc/config/testsuite/META-INF/roaster-[profile-name].yml` configuration files

== Release

The release process is automated and managed by GitHub Actions.
During each release, not only are Maven artifacts built and published, but Docker images are also prepared and released.

=== Maven release

The Maven release is generated and uploaded to Sonatype for distribution. You can find the released Maven artifacts at:
https://central.sonatype.com/namespace/hu.icellmobilsoft.dookug[DookuG Backend - Maven Artifacts]

=== Docker Release

For Docker releases, both the Dockerfile and the docker-compose file are located in the `./etc/release` directory.
The released Docker images are pushed to Docker Hub and can be found at the following links:

- https://hub.docker.com/r/icellmobilsoft/dookug-document-service-postgres[DookuG Document Service with PostgreSQL]
- https://hub.docker.com/r/icellmobilsoft/dookug-document-service-oracle[DookuG Document Service with Oracle]
