<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>hu.icellmobilsoft.dookug.testsuite</groupId>
        <artifactId>dookug-ts-common</artifactId>
        <version>2.2.0-SNAPSHOT</version>
    </parent>

    <name>${project.artifactId}</name>
    <artifactId>dookug-ts-common-db</artifactId>

    <dependencies>
        <dependency>
            <groupId>hu.icellmobilsoft.dookug</groupId>
            <artifactId>dookug-model</artifactId>
        </dependency>
        <dependency>
            <groupId>hu.icellmobilsoft.roaster</groupId>
            <artifactId>roaster-hibernate</artifactId>
        </dependency>
        <dependency>
            <groupId>org.postgresql</groupId>
            <artifactId>postgresql</artifactId>
        </dependency>
<!--        <dependency>-->
<!--            <groupId>org.hibernate</groupId>-->
<!--            <artifactId>hibernate-validator</artifactId>-->
<!--        </dependency>-->
    </dependencies>


</project>