= Using Custom Fonts

This documentation is intended for the https://pdfbox.apache.org/[Apache PDFBox] engine and focuses on using custom fonts.
[NOTE]
====
A limitation of the engine is that it can only embed TTF fonts. Additionally, if you want to use weight, styles, and variants settings, it is worth noting that PDFBox cannot always emulate these properly unless you load different variations of the font.

====
In the docker-compose file, we add the `fonts` directory to our image as `/home/icellmobilsoft/fonts`, so we can access the fonts in this directory locally from the templates.

We have two options for using custom fonts.

. Load the font directly in the CSS
. Load the font programmatically, then reference it in the CSS using `font-family`

In the first option, you can specify the font's location in the CSS within the `@font-face` at-rule using the `src: url()` descriptor.

In this case, internet access will be required during generation, which may not always be possible as the company's policy may prohibit the module from accessing external URLs.

This can be mitigated either by making the fonts accessible through an internal URL or by preloading some frequently used fonts in the module and referencing their local availability using a `file://` URL.
If the module will contain preloaded fonts, it is advisable to mention this in the documentation or provide the information through an endpoint.

TEMPLATE:
[source,xml]
----
<style>
    @font-face {
        font-family: 'Cairo';
        font-style: normal;
        src: url(file:/home/icellmobilsoft/fonts/Cairo/Cairo-Regular.ttf); // <1>
    }

    @font-face {
        font-family: 'IndieFlower';
        font-style: normal;
        src: url(file:fonts/IndieFlower/IndieFlower-Regular.ttf); // <2>
    }
</style>
----
<1> Loading Cairo-Regular.ttf from the `/home/icellmobilsoft/fonts` directory.
<2> Here we also load the font from the above directory. The server considers `/home/icellmobilsoft` as the root, so the relative path works.

[TIP]
====
Using Google Fonts

[source,xml]
----
<style>
    @import url('https://fonts.googleapis.com/css?family=Quicksand&amp;display=swap'); // <1>

    .quicksand { // <2>
      font-family: 'Quicksand', Arial;
      font-weight: 700;
      font-style: normal;
      font-size: 38px;
      line-height: 1.15;
      letter-spacing: -.02em;
      color: rgba(0, 0, 0, 0.8);
      -webkit-font-smoothing: antialiased;
    }
</style>
...
<p class="quicksand">Google Quicksand Font úőüöóéáyí</p> // <3>

----
<1> Importing the Quicksand font from https://fonts.google.com/[Google Fonts]
<2> Setting the CSS class to use the font
<3> Displaying text with the specified font

====



If we want to load fonts programmatically from the file system, we can use the `builder.useFonts` method during rendering, which we can reference in the CSS.

JAVA:
[source,java]
----
builder.useFont(new File("fonts/NotoSansThai/NotoSansThai-Regular.ttf"), "notosansthai-regular"); // <1>
----
<1> Loading NotoSansThai-Regular.ttf

TEMPLATE:
[source,xml]
----
<style>
    @font-face {
        font-family: 'notosansthai-regular'; // <1>
        font-style: normal;
        -fs-font-subset: complete-font; // <2>
    }
</style>
----
<1> Using the previously loaded font
<2> This is just an example; this setting is not really necessary as it embeds the entire font, whereas by default only the subset is embedded, which is the correct operation.


The downside is that all fonts are loaded during rendering, even those not used in the document template.


[NOTE]
====
The PDFBox Fonts Wiki is available https://github.com/danfickle/openhtmltopdf/wiki/Fonts[here]

====