[[pdf-digital-signature]]
= Digitally Signing PDFs

This documentation is intended for the https://pdfbox.apache.org/[Apache PDFBox] engine and describes the process of digitally signing PDFs using a self-signed certificate, which is added to the image as `/home/icellmobilsoft/keys/keystore.p12` using the docker-compose file.

The keystore is located in the `/etc/docker-compose/keys` folder and was created on November 7, 2023, with the following command:

[source,text]
----
keytool -genkeypair -storepass 123456 -storetype pkcs12 -alias test -validity 10958 -v -keyalg RSA -keystore keystore.p12
----

[WARNING]
====
it will expire on November 7, 2053.

====

== Configuration

The signature can be requested in the API calls within the GeneratorSetup request. Here you can specify the `signatureName`, `signatureReason`, and the private key alias (`keyAlias`) in case the keystore file contains multiple private keys.

[source,xml]
----
...
<ns2:generatorSetup>
    <ns2:generatorEngine>PDF_BOX</ns2:generatorEngine>
    <ns2:templateEngine>NONE</ns2:templateEngine>
    <ns2:responseFormat>PDF</ns2:responseFormat>
    <ns2:digitalSignatureProfile>sampleProfile</ns2:digitalSignatureProfile> <1>
        ...
----
<1> The name of the signature profile only in case you need PDF signing

The signature can be customized with the following configuration keys:
[source,yaml]
----
dookug:
  service:
    engine:
      pdf:
        digitalsign:
          sampleProfile: <1>
            name: Example Ltd. <2>
            reason: Certified <2>
            keystore: /home/icellmobilsoft/keys/keystore.p12 <3>
            keystorePass: 123456 <4>
            keystoreType: PKCS12 <4>
            keyAlias: key_test <5>
----
<1> the name of the signatureProfile
<2> `name` and `reason` default values are used if the request does not contain these values.
<3> `keystore` is mandatory and specifies the location of the signing keys.
<4> `keystorePass` and `keystoreType` specify the password and type of the keystore file, respectively. These are also mandatory.
<5> the identifier of the private key within the keystore

== Changing Certificates

If you need to replace the certificate used for digital signing (e.g., due to expiration), follow these steps:

- mount the new keystore file as a docker volume
- edit the xref:../install/dookug-service.adoc#pdf-signing-config[configurations of digital signing] if necessary

No application release is required. Restarting the service with the new certificate is sufficient.

== Visible signature (using the EU DSS ESIGN library)

In case you want to add visible (clickable) signature to the PDF document you need to add some extra configuration.

----
dookug:
  service:
    engine:
      pdf:
        digitalsign:
          sampleProfile:
            keystore: /home/icellmobilsoft/keys/keystore.p12 <1>
            keystorePass: 123456
            keystoreType: PKCS12
            keyAlias: key_test
            useEuDssSig: true <2>
            dss:
              imageFile: /home/icellmobilsoft/pdfsign/sample/signature.png <3>
              showOnPage: 1 <4>
              position:
                left: 18 <5>
                top: 2 <6>
              width: 2 <7>
              useTimestamp: true <8>
              tspSources:
                - http://timestamp.digicert.com <9>
              useLT: true <10>
              useLTA: false <11>
              encryptionAlgorithm: RSA <12>
              digestAlgorithm: SHA-256 <13>
              certificationPermission: NO_CHANGE_PERMITTED <14>
----
<1> the keystore file
<2> use the EU DSS library to sign the document
<3> the image you want to add to the document
<4> the image will added to this page: `-1`: last page, `1`:first page, `0`:wont add, `n`:n-th page 
<5> X position of the image in cm (from top left corner)
<6> Y position of the image in cm (from top left corner)
<7> the width of the image in cm
<8> you can add the signature timestamp to the image
<9> timestamp server for LT/LTA
<10> for PAdES BASELINE LT
<11> for PAdES BASELINE LTA
<12> encryption algorithm used for private key (for example: RSA, ECDSA)
<13> digest algorithm used for private key
<14> certification permission can be set optionally. The values can be: NO_CHANGE_PERMITTED | MINIMAL_CHANGES_PERMITTED | CHANGES_PERMITTED 

The available configuration keys can be found <<pdfSignatureConfiguration,here>>.

[IMPORTANT]
====
If we need PAdES BASELINE T, LT or LTA, the tspSources must be given!
====

PAdES BASELINE T: tspSources must be set 

PAdES BASELINE LT: tspSources must be set and useLT=true

PAdES BASELINE LTA: tspSources must be set and useLTA=true

[IMPORTANT]
====
If we set the certificationPermission, the PDF document will be certified and not signed in Adobe Acrobat Reader! 
====

== Simple signature (using the PdfBox ESIGN library)

For legacy using there is an option to use the pdfbox engine for simple digital signing. 

----
dookug:
  service:
    engine:
      pdf:
        digitalsign:
          sampleProfile:
            keystore: /home/icellmobilsoft/keys/keystore.p12 <1>
            keystorePass: 123456
            keystoreType: PKCS12
            keyAlias: key_test
            pdfBox:
              signatureAlgorithm: SHA256WithRSA <2>
----
<1> the keystore file
<2> the certificate algorithm used for the pdfbox engined digital signing (not DSS!). For example: `SHA256withECDSA` Default: `SHA256WithRSA`

[NOTE]
====
Here you can find the available signature algorithm identifiers

https://github.com/bcgit/bc-java/blob/main/pkix/src/main/java/org/bouncycastle/operator/DefaultSignatureAlgorithmIdentifierFinder.java#L745

====
 

The available configuration keys can be found <<pdfSignatureConfiguration,here>>.

