{
 "title": "DookuG backend base",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Up time",
   "type": "stat",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "base_jvm_uptime_seconds{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU available core",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "base_cpu_availableProcessors{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU load [%] / core",
   "type": "timeseries",
   "description": "https://scoutapm.com/blog/understanding-load-averages",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "base_cpu_processCpuLoad{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Thread",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "base_thread_count{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Up",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 22, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory [MiB]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "base_memory_usedHeap_bytes{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CG Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "rate(base_gc_time_total_seconds{instance=\"$instance\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DS available",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_available_count{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DS pool in use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 25 },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_in_use_count{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DS pool active count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 5, "x": 11, "y": 25 },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_active_count{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DS blocking time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_total_blocking_time{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DS pool timed out",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 25 },
   "targets": [
    {
     "expr": "wildfly_datasources_pool_timed_out{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}