{
 "title": "DookuG backend memory usage",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "Generic memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory - maxHeap [MiB]",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "base_memory_maxHeap_bytes{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory - usedHeap [MiB]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "base_memory_usedHeap_bytes{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CG Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 14, "y": 1 },
   "targets": [
    {
     "expr": "rate(base_gc_time_total_seconds{instance=\"$instance\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory - committedHeap [MiB]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "base_memory_committedHeap_bytes{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory - maxNonHeap [MiB]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "base_memory_maxNonHeap_bytes{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory - committedNonHeap [MiB]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "base_memory_committedNonHeap_bytes{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory - usedNonHeap [MiB]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "base_memory_usedNonHeap_bytes{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory - metaSpaceUsage [MiB]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "vendor_memoryPool_Metaspace_usage_bytes{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory - CompressedClassSpaceUsage [MiB]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "vendor_memoryPool_Compressed_Class_Space_usage_bytes{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory - memoryPool_CodeHeapUsage [MiB]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "vendor_memoryPool_CodeHeap__non_nmethods__usage_bytes{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "G1GC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Memory - G1EdenSpaceUsage [MiB]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "vendor_memoryPool_G1_Eden_Space_usage_bytes{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory - G1OldGenUsage [MiB]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "vendor_memoryPool_G1_Old_Gen_usage_bytes{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory - G1SurvivalUsage [MiB]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "vendor_memoryPool_G1_Survivor_Space_usage_bytes{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "ZGC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Memory - ZHeapUsageUsage [MiB]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "vendor_memoryPool_ZHeap_usage_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory - ZHeapUsageUsageMax [MiB]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "vendor_memoryPool_ZHeap_usage_max_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "SerialGC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Memory - edenSpaceUsage [MiB]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "vendor_memoryPool_Eden_Space_usage_bytes{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory - survivalSpaceUsage [MiB]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "vendor_memoryPool_Survivor_Space_usage_bytes{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory - tenuredGenUsage [MiB]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "vendor_memoryPool_Tenured_Gen_usage_bytes{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "ParallelGC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 } },
  {
   "title": "Memory - PSSurvivorSpaceUsage [MiB]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "vendor_memoryPool_PS_Survivor_Space_usage_bytes{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory - PSEdenSpaceUsage [MiB]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 10, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "vendor_memoryPool_PS_Eden_Space_usage_bytes{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory - PSOldGenSpaceUsage [MiB]",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "vendor_memoryPool_PS_Old_Gen_usage_bytes{instance=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}