# run from project directory
# docker compose -f ./etc/docker-compose/docker-compose.local.postgredb.yml up --build --force-recreate
#
# enter container
# docker exec -it module-dookug-postgredb /bin/bash
services:
  module-dookug-postgredb:
    container_name: module-dookug-postgredb
    image: icellmobilsoft/db-base-postgres_148:${DBDWH_IMAGE_VERSION}
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - module-dookug-postgredb-data:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD', 'pg_isready' ]
      interval: 2s

  ##run liquibase
  dookug-liquibase:
    container_name: module-dookug-liquibase
    image: icellmobilsoft/dookug_db:${DOOKUG_LIQUIBASE_VERSION}
    environment:
      AUTO_INSTALL: postgresql
    depends_on:
      module-dookug-postgredb:
        condition: service_healthy

networks:
  default:
    external: true
    # if missing: docker network create dookug-local-network
    name: dookug-local-network
volumes:
  module-dookug-postgredb-data:
    name: module-dookug-postgredb-data
