# run from project directory
# docker compose -f ./etc/docker-compose/docker-compose.local.dookug-document-service.oracle.yml up --build --force-recreate
#
# enter container
# docker exec -it dookug-document-service /bin/bash
services:
  dookug-document-service-developer:
    container_name: dookug-document-service
    image: icellmobilsoft/wildfly-mp-jpa-postgresql-jdbc:${WILDFLY_IMAGE_VERSION}
    volumes:
      - './fonts/:/home/icellmobilsoft/fonts'
      - './fop-config/:/home/icellmobilsoft/fop-config'
      - './keys/pdf/keystore.p12:/home/icellmobilsoft/keys/keystore.p12'
      - './pdfsign/sample/signature-green.png:/home/icellmobilsoft/pdfsign/sample/signature.png'
      - './handlebars/helper/js:/home/icellmobilsoft/handlebars/helper/js'
    ports:
      - '8082:8080'
      - '9992:9990'
      - '8789:8787'
    environment:
      org_apache_deltaspike_ProjectStage: Development
      CONSOLE_LOGGING_JSON_ENABLED: false
      CONSOLE_LOGGING_ENABLED: true
      LOGSTASH_ENABLED: false
      DEBUG: true
      HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      POSTGRESQL_DS_CONNECTION_URL: jdbc:postgresql://module-dookug-postgredb:5432/dookug_db?currentSchema=dookug
      POSTGRESQL_DS_USERNAME: postgres
      POSTGRESQL_DS_PASSWORD: postgres
      DOOKUG_SERVICE_ENGINE_PDF_DIGITALSIGN_SAMPLEDSS_KEYSTOREPASS: 123456
      DOOKUG_SERVICE_ENGINE_PDF_DIGITALSIGN_SAMPLEDSS_KEYALIAS: 'test'
      DOOKUG_SERVICE_ENGINE_PDF_DIGITALSIGN_SAMPLEPROFILE_KEYSTOREPASS: 123456
      DOOKUG_SERVICE_ENGINE_PDF_DIGITALSIGN_SAMPLEPROFILE_KEYALIAS: 'test'
      DOOKUG_SERVICE_ENGINE_PDF_DIGITALSIGN_SAMPLEPROFILE_KEYSTORE: /home/icellmobilsoft/keys/keystore.p12
      DOOKUG_SERVICE_ENGINE_PDF_DIGITALSIGN_SAMPLEPROFILE_USEEUDSSSIG: true
      DOOKUG_SERVICE_ENGINE_PDF_DIGITALSIGN_SAMPLEPROFILE_DSS_USELT: false
      DOOKUG_SERVICE_ENGINE_PDF_DIGITALSIGN_SAMPLEPROFILE_DSS_TSPSOURCES: http://timestamp.digicert.com
      DOOKUG_SERVICE_ENGINE_PDF_DIGITALSIGN_SAMPLEPROFILE_DSS_IMAGEFILE: /home/icellmobilsoft/pdfsign/sample/signature.png
      DOOKUG_SERVICE_ENGINE_PDF_DIGITALSIGN_SAMPLEPROFILE_DSS_SHOWONPAGE: 0
      
#      OPENTRACING_JAEGER_AGENT_HOST: jaeger
#      JAEGER_SERVICE_NAME: dookug-document-service
      OPENTELEMETRY_SERVICE_NAME: dookug-document-service
      # alternative config
#      OTEL_SERVICE_NAME: bs-sample-service
      OPENTELEMETRY_SAMPLER_TYPE: on # default is ratio with 0.01
      # 1. -> jaeger, hagyomanyos
      #OPENTELEMETRY_EXPORTER_ENDPOINT: http://jaeger:14250
      # 2. -> jaeger otlp
      #OPENTELEMETRY_EXPORTER_TYPE: otlp # default is jaeger
      #OPENTELEMETRY_EXPORTER_ENDPOINT: http://jaeger:4317
      # 3. -> otlp-collector -> jaeger otlp
      OPENTELEMETRY_EXPORTER_TYPE: otlp # default is otlp, "The 'jaeger' exporter is no longer supported.", but the docs say its allowed
      OPENTELEMETRY_EXPORTER_ENDPOINT: http://opentelemetry-collector:4317
      MICROMETER_ENDPOINT: http://opentelemetry-collector:4318/v1/metrics

    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M
networks: 
  default:
    external: true
    # if missing: docker network create dookug-local-network
    name: dookug-local-network
