services:
    prometheus:
        container_name: prometheus
        volumes:
            - '../config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
        image: prom/prometheus:v2.45.3
        ports:
            - '9090:9090'
    grafana:
        container_name: grafana
        volumes:
            - '../config/grafana/provisioning/:/etc/grafana/provisioning/'
        image: grafana/grafana:10.3.1
        ports:
            - '3000:3000'
    jaeger:
        container_name: jaeger
        image: jaegertracing/all-in-one:1.54.0
        volumes:
            - '../config/jaeger/sampling_strategies.json:/etc/jaeger/sampling_strategies.json'
        ports:
            - '6831:6831/udp'
            - '16686:16686'
    opentelemetry-collector:
        container_name: opentelemetry-collector
        #TODO collector "The number of requests this listener has served" but should have "Number of all requests"
        image: otel/opentelemetry-collector:0.123.0
        # contrib collector repo e.g. tail_sampling processor
        # https://github.com/open-telemetry/opentelemetry-collector-contrib
        # image: otel/opentelemetry-collector-contrib:0.123.0
        command: [--config=/etc/otel-collector-config.yaml]
        volumes:
            - ../config/opentelemetry/otel-collector-config.yaml:/etc/otel-collector-config.yaml
#            - ../config/opentelemetry/otel-collector-probabilistic-sampling-config.yaml:/etc/otel-collector-config.yaml
#            - ../config/opentelemetry/otel-collector-tail-sampling-config.yaml:/etc/otel-collector-config.yaml
            # example sampling strategies to otelcol 
            - ../config/jaeger/sampling_strategies.json:/etc/otelcol/sampling_strategies.json
        ports:
            - 1888:1888 # pprof extension
            - 8888:8888 # Prometheus metrics exposed by the collector
            - 8889:8889 # Prometheus exporter metrics
            - 13133:13133 # health_check extension
            - 4317:4317 # OTLP gRPC receiver
            - 4318:4318 # OTLP http receiver
            - 55679:55679 # zpages extension
            - 1234:1234 # /metrics endpoint
networks:
  default:
    external: true
      # if missing: docker network create dookug-local-network
    name: dookug-local-network
