= DOOKUG-DOCUMENT Service

== Document Generation

The module provides multiple options for document generation. For each option, we can specify:

* The generator setup (`request.generatorSetup`):
** Template engine for parameter substitution (NONE, HANDLEBARS) (`request.generatorSetup.templateEngine`)
** Document generator engine (NONE, PDF_BOX, SAXON) (`request.generatorSetup.generatorEngine`)
** Response format (STRING, PDF) (`request.generatorSetup.responseFormat`)
** Storage type (NONE, DATABASE)
** Optional parameters (`request.generatorSetup.parameters` or `request.generatorSetup.parametersData.templateParameters` or `request.generatorSetup.parametersData.generatorParameters`)
** Optional digital signature profile (`request.generatorSetup.digitalSignatureProfile`)
** Optional template language, in case of inline SAXON generation (`request.generatorSetup.templateLanguage`)
** Template, in case of a stored one, specifying the following attributes for finding it in cache or the database,
or for SAXON generation, choosing the language within the XSLT:
*** `templateName`
*** `templateLanguage`
*** Optional `validityDate`

* The templates (`request.templates`), as list of `TemplateType` objects, in case of inline generation,
specifying the `templateName`, `templateContent` in base64 binary format and the `inital` flag, representing the initial template and other template parts

Firstly, the generator setup is validated based on the response format
and the generator engine:

* If the response format is PDF, then the generator engine can only be PDF_BOX or SAXON
* If the response format is STRING, then the generator engine can only be NONE

Secondly, in the template compilation phase the following scenarios can occur, based on the template engine,
the parameters or parametersData:

* If the template engine is HANDLEBARS, then compilation takes place:
** If parameters are provided (key - value pairs) OR
** If parametersData is provided (json key - value pairs in base64 binary format, can be zipped as well (GZIP)) OR
** No parameters are provided (compilation with empty context)
* If the template engine is NONE:
** You can send only one template in the templates list with no parameters or parametersData
** No compilation will occur

Thirdly, on document generation, optional signing and optional storage:

* The document stream is created if the generator engine is PDF_BOX or SAXON:
** PDF_BOX:
*** The document is created by the compiled html
*** Optionally the document can be signed if the digital signature profile was provided in the request
** SAXON:
*** With this generator the compilation happens during generation by the provided parametersData (`request.generatorSetup.parametersData.generatorParameters`)
*** Optionally the document can be signed if the digital signature profile was provided in the request
*** NOTE: It is possible to combine SAXON with HANDLEBARS. This way you can compile XSLT templates dynamically:
**** Set the template engine to HANDLEBARS and the generator to SAXON
**** Provide XSLT template parts in the templates list (main template can contain HANDLEBARS placeholders)
**** Provide XSLT template parameters in the generatorSetup.parametersData

* Storage, based on storage method type
** DATABASE:
*** The document is saved with parameters, parametersData or null parametersData and the document is returned
** NONE:
*** The document is returned

[[generateInline]]
== Document generation based on request body

[source,text]
----
POST /internal/dookug/document/generate/inline
----

During generation, we submit the initial template and the data associated with the generation in the request body: template and engine processing the document, response format, and document storage method.

In the response, we receive the generated document and the filename in the HTTP header.

[[generateInlineMetadata]]
== Document generation based on request body, with metadata response

[source,text]
----
POST /internal/dookug/document/generate/inline/metadata
----

There's an option to receive metadata describing the document instead of the document itself. In this case, the request URI and HTTP header differ when submitting the request.

[[generateInlineMultipart]]
== Document generation based on multipart form

[source,text]
----
POST /internal/dookug/document/generate/inline/multipart
----

To generate, we need to submit the initial template and the data associated with the generation. The latter matches the data sent for document generation based on the request body.

In the response, we receive the generated document and the filename in the HTTP header.

[[generateInlineMultipartMetadata]]
== Document generation based on multipart form, with metadata response

[source,text]
----
POST /internal/dookug/document/generate/inline/multipart/metadata
----

There's also an option to receive metadata describing the document instead of the document itself. In this case, the request URI and HTTP header differ when submitting the request.

[[generateStored]]
== Document generation based on stored template

[source,text]
----
POST /internal/dookug/document/generate/storedTemplate
----

To generate, we need to submit the name of the template from which the document is generated, along with the data associated with the generation. The latter matches the data sent for document generation based on the request body, supplemented with how the template is stored.

In the response, we receive the generated document and the filename in the HTTP header.

[[generateStoredMetadata]]
== Document generation based on stored template, with metadata response

[source,text]
----
POST /internal/dookug/document/generate/storedTemplate/metadata
----

There's an option to receive metadata describing the document instead of the document itself. In this case, the request URI and HTTP header differ when submitting the request.

The template key stored in the database consists of the templateName and templateLanguage values.

'''

Saving the document depends on the `documentStorageMethod` parameter. It can take two values: `NONE` and `DATABASE`. If `NONE` is specified, the document is not saved, and therefore cannot be queried later. In case of `DATABASE`, the generated document is saved in a database table, from where it can be retrieved later. Other data related to the document are also saved in the database:

* identifier of the initial template - if the template is not saved, this parameter is not filled
* filename of the generated file - generated from the unique identifier of the document, the name of the initial template, and the timestamp of the generation long value
* file format
* document status - DONE, FAILED, PENDING, SYNCING
* parameters related to the document
* document storage format - in case of the field DATABASE, this field is also filled with DATABASE value

'''

During generation, the initial template is provided in any form of the response, the generated file is received, or metadata describing the document is received, as a DocumentMetadataResponse type object.

[[queryDocumentMetadata]]
== Query Document Metadata

[source,text]
----
POST /internal/dookug/document/storedTemplate/metadata/query
----

The purpose of querying document metadata is to retrieve document information that meets the specified filtering criteria.

The endpoint supports pagination, meaning data can be retrieved across multiple pages. 
In the request, you can specify which page of data and how many elements per page you want to retrieve. 
Accordingly, the response includes total count of elements and the number of pages they span.
If not specified, the endpoint defaults to returning the first 15 elements.

The following filtering criteria can be used:

* templateId - identifier of the template used for document generation
* status - status of the document
* format - file format of the document
* storageMethod - storage method of the document
* storageId - unique identifier of the document storage
* filename - name of the document file

Sorting parameters can be:

* filename
* documentStorageMethod
* format
* status

For sorting, you can specify whether to sort in ascending or descending order for each parameter individually.
In addition to the mentioned sorting options, there is a default sorting by document identifier.

If documents are found based on the submitted parameters, the response returns a list of up to 100 elements.

[[getDocument]]
== Get Document

[source,text]
----
GET /internal/dookug/document/content/{documentId}
----

The purpose of this endpoint is to retrieve a previously generated and saved document based on the provided identifier.

If no document is found for the submitted identifier, an ENTITY_NOT_FOUND error is returned.

In the response - for an existing document identifier - the generated document is returned, and the file name is included in the HTTP headers.


[[signPdfDocument]]
== Electronic document signing (PDF) 

[source,text]
----
POST /internal/dookug/document/sign/inline/multipart
----

The document received in the request is digitally signed and returned in the response. The request must include the file to be signed and the name of the signing profile. The signing process is performed synchronously based on the parameters configured in the module for the given profile. The file is not stored on the server at any point.

In the response, we receive the signed document and the filename in the HTTP header. The filename can be set in the request. 
