= v2.1.0

== Changes / updates

* The response context includes the original requestId when it is applicable
* Documentation fixes regarding OPENTELEMETRY_SAMPLER_TYPE and OPENTELEMETRY_SAMPLER_RATIO environment variables
* The `dookug.service.interface.parametersdata.gzipped` config default value changed to `true`, and with the true value the backend can process compressed and uncompressed parameters too.
* Option to download generated documents in compressed (GZIP) format by setting the `responseContentGzipped` URL query parameter to `true` for the following endpoints:
** xref:../service/document.adoc#getDocument[Get Document]
** xref:../service/document.adoc#generateInline[Document generation based on request body]
** xref:../service/document.adoc#generateInlineMultipart[Document generation based on multipart form]
** xref:../service/document.adoc#generateStored[Document generation based on stored template]
** On the Java Client it can be controlled by the client's `setResponseContentGzipped` method.
By default, it is `false`.
* OSS Sonatype -> Maven Central repository migration
* `parent-oss-pom` upgrade *1.4.0 -> 1.5.0*
* `docker-base` upgrade *1.5.0 -> 1.7.0*
** including `builder-nexus-download` and setting the `NEXUS_REPOSITORY_TYPE=central` environment variable in release Dockerfiles

== Migration

Changes are backwards compatible, doesn't need any migration.
