= Digitally Signing PDFs

This documentation is intended for the https://pdfbox.apache.org/[Apache PDFBox] engine and describes the process of digitally signing PDFs using a self-signed certificate, which is added to the image as `/home/icellmobilsoft/keys/keystore.p12` using the docker-compose file.

The keystore is located in the `/etc/docker-compose/keys` folder and was created on November 7, 2023, with the following command:

[source,text]
----
keytool -genkeypair -storepass 123456 -storetype pkcs12 -alias test -validity 10958 -v -keyalg RSA -keystore keystore.p12
----

[WARNING]
====
This means it will expire on November 7, 2053.

====

== Configuration

The signature can be requested in the API calls within the GeneratorSetup request. Here you can specify the `signatureName`, `signatureReason`, and the private key alias (`keyAlias`) in case the keystore file contains multiple private keys.

[source,xml]
----
...
<ns2:generatorSetup>
    <ns2:generatorEngine>PDF_BOX</ns2:generatorEngine>
    <ns2:templateEngine>NONE</ns2:templateEngine>
    <ns2:responseFormat>PDF</ns2:responseFormat>
    <ns2:addDigitalSignature>
        <ns2:signatureName>TestSuite name</ns2:signatureName>
        <ns2:signatureReason>TestSuite test reason</ns2:signatureReason>
        <ns2:signatureProfile>sampleProfile</ns2:signatureProfile>
    </ns2:addDigitalSignature>
        ...
----

The signature can be customized with the following configuration keys:
[source,yaml]
----
dookug:
  service:
    engine:
      pdf:
        digitalsign:
          signature:
            sampleProfile: <1>
              name: Example Ltd. <2>
              reason: Certified <2>
              keystore: /home/icellmobilsoft/keys/keystore.p12 <3>
              keystorePass: 123456 <4>
              keystoreType: PKCS12 <4>
              keyAlias: key_test <5>
----
<1> the name of the signatureProfile
<2> `name` and `reason` default values are used if the request does not contain these values.
<3> `keystore` is mandatory and specifies the location of the signing keys.
<4> `keystorePass` and `keystoreType` specify the password and type of the keystore file, respectively. These are also mandatory.
<5> the identifier of the private key within the keystore

== Visible signature (using the EU DSS ESIGN library)

In case you want to add visible (clickable) signature to the PDF document you need to add some extra configuration.

----
dookug:
  service:
    engine:
      pdf:
        digitalsign:
          signature:
            sampleProfile:
              name: Example Ltd.
              reason: Certified
              keystore: /home/icellmobilsoft/keys/keystore.p12 <3>
              keystorePass: 123456
              keystoreType: PKCS12
              keyAlias: key_test
              dss: <1>
                imageFile: /home/icellmobilsoft/pdfsign/sample/nusz_signature.png <2>
                page: 1 <3>
                left: 18 <4>
                top: 2 <5>
                width: 2 <6>
                useTimestamp: false <7>        
              
----
<1> the key for DSS library
<2> the image you want to add to the document
<3> the image will added to this page: `-1`: last page, `1`:first page, `0`:wont add, `n`:n-th page 
<4> X position of the image in cm
<5> Y position of the image in cm
<6> the width of the image in cm
<7> you can add the signature timestamp to the image

The available configuration keys can be found <<pdfSignatureConfiguration,here>>.
