= Helpers - Helper Functions for Use in Template Files

== Built-in Helpers

Handlebars provides built-in helpers, whose documentation can be found https://handlebarsjs.com/guide/builtin-helpers.html[here].

== Custom Helpers

It is possible to use general helpers provided by the module. In the examples, the ... parts render if the expression evaluates to true.

=== Usage

When using helpers, specify the parameters for the given helper after the helper keyword. Helpers can be used during inline generation and database-stored template-based generation. The parameters can be hardcoded values or come in JSON format during the document generation call.

Helpers can be combined with each other.

[cols="5%,45%,45%a,5%"]
|===
|Token | Description | Usage | Available from Version |

equals |
Compares the values of two elements; renders if the evaluation is true. |
[source,bash]
----
{{#if (equals yourField 'white')}} ... {{/if}}
----
|
0.1.0 |

before |
Renders if the provided parameter is an earlier date than the given value. The latter can also be a parameter. |
[source,bash]
----
{{#if (before yourDate '2023-08-13T05:40:55Z')}} ... {{/if}}
{{#if (before yourDate checkDate)}} ... {{/if}}
----
|
0.1.0 |

between |
Renders if the provided parameter falls between the two given date values. The latter can also be parameters. |
[source,bash]
----
{{#if (between yourDate '2023-08-13T05:40:55Z' '2023-08-15T05:40:55Z')}} ... {{/if}}
{{#if (between yourDate startDate endDate)}} ... {{/if}}
----
|
0.1.0 |

dateMinusMinutes |
Subtracts a given number of minutes from the specified date. |
[source,bash]
----
{{dateMinusMinutes '2023-08-13T05:40:55Z' 60}}    // evaluates to '2023-08-13T04:40:55Z'
{{dateMinusMinutes yourDate 60}}                  // The following two examples evaluate to the same date
{{dateMinusMinutes yourDate minutesToSubtract}}
----
|
0.1.0 |

datePlusMinutes |
The counterpart to dateMinusMinutes, it adds minutes to the given date. |
[source,bash]
----
{{datePlusMinutes '2023-08-13T05:40:55Z' 60}} - evaluates to '2023-08-13T06:40:55Z'
{{datePlusMinutes yourDate 60}}
{{datePlusMinutes yourDate minutesToAdd}}
----
|
0.1.0 |

declare |
Creates a new variable and immediately renders it. The created variables are global, regardless of where they were created in the templates. |
[source,bash]
----
{{declare 'myColor' 'white'}}       // immediately renders the word 'white'
...
{{#if myColor}} {{myColor}} {{/if}} // renders 'white'
----
|
0.1.0 |

declareVoid |
Works similarly to the declare helper, but does not immediately render the given value. declare can be replaced by declareVoid followed by immediate invocation. |
[source,bash]
----
{{declareVoid 'myColor' 'white'}}
...
{{#if myColor}} {{myColor}} {{/if}}  // renders 'white'
Replacing declare with declareVoid:
{{declareVoid 'myColor' 'white'}}
{{myColor}}   // renders 'white' immediately after creation
----
|
0.1.0 |

formatDate |
Transforms the given parameter, accepted in Java 8 date format, according to the specified pattern. The pattern only accepts date formats; otherwise, it throws an error. |
[source,bash]
----
yourDate = '2024-01-09';

{{formatDate '2023-08-13' 'yyyy.MM.dd'}}         // '2023.08.13'
{{formatDate '2023-08-13' 'MM.dd.yyyy'}}         // '08.13.2023'
{{formatDate yourDate 'yyyy/MM/dd'}}             // '2024/01/09'
----
|
0.5.0 |

formatDateTime |
Transforms the given parameter, accepted in Java 8 date and time format, according to the specified pattern. The helper handles full ISO date format input and can generate appropriate output using the pattern. The helper can also handle time zones; if a Java-accepted Zone ID is provided after the output pattern, it converts the input time to the time zone's output. |
[source,bash]
----
yourDate = '2024-01-09T15:30:04Z'
yourDateTimeFormat = 'MM.dd-HH:mm'
yourDateFormat = 'yyyy/MM.dd'
yourTimeFormat = 'hh:mm:ss a'

{{formatDateTime '2023-08-13T05:40:55Z' 'yyyy-MM-dd HH:mm:ss'}}         // '2023-08-13 06:40:55'
{{formatDateTime yourDate 'yyyy-MM-dd HH:mm:ss'}}                       // '2024-01-09 15:30:04'
{{formatDateTime yourDate yourDateTimeFormat}}                          // '01.09-15:30'
{{formatDateTime yourDate yourDateFormat}}                              // '2024/01.09'
{{formatDateTime yourDate yourTimeFormat}}                              // '03:30:04 PM'
{{formatDateTime '2023-08-13T05:40:55Z' 'yyyy-MM-dd HH:mm:ss' 'CET'}}   // '2023-08-13 08:40:55'
----
|
0.5.0 |

formatTime |
Transforms the given parameter, accepted in Java 8 time format, according to the specified pattern. The pattern only accepts time formats; otherwise, it throws an error. |
[source,bash]
----
yourTime = '15:30:55Z';

{{formatTime '15:30:55Z' 'HH:mm:ss'}}         // '15:30:55'
{{formatTime yourTime 'h:mm A'}}              // '3:30 PM'
----
|
0.5.0 |

formatNumber |
Helper used for formatting numbers, following Java number formatting conventions. |
[source,bash]
----
number = 1234.567;
percentage = 0.4567

{{formatNumber number '#'}}         // "1235", rounded integer
{{formatNumber number '0.00'}}      // "1234.57", number rounded to 2 decimals
{{formatNumber number '000000.00'}} // "001234.57", number padded with leading zeros
{{formatNumber number '#,###.##'}}  // "1,234.57", comma-separated, grouped by thousands
{{formatNumber number '$#,##0.00'}} // "$1,234.57", currency expression
{{formatNumber percentage '0.00%'}} // "45.67%", percentage expression of a value between 0 and 1
{{formatNumber number '0.###E0'}}   // "1.235E8", number in scientific notation
----
|
0.1.0 |

and |
Logical AND operator for N values. Renders if the logical AND operator evaluates to true. |
[source,bash]
----
{{#if (and falseValue trueValue notExistingValue)}} YES {{else}} NO {{/if}}               // renders "NO"
{{#if (and trueValue trueValue trueValue)}} YES {{/if}}                                   // renders "YES" since all three values are true
myValue = 'black'
{{#if (and (equals myValue 'black')}} YES {{else}} NO {{/if}}                             // renders "YES", both the variable and the string evaluation are true
{{#if (and (equals myValue 'white')}} YES {{else}} NO {{/if}}                             // renders "NO", both the variable and the string evaluation are false

Combined usage:
{{#if (and (equals 'black' 'white') (equals 'white' 'white'))}} YES {{else}} NO {{/if}}   // renders "NO", the first is false, the second is true
----
|
0.1.0 |

or |
Logical OR operator for N values. Renders if the logical OR operator evaluates to true. |
[source,bash]
----
{{#if (or falseValue trueValue notExistingValue)}} YES {{else}} NO {{/if}}               // renders "YES"
{{#if (or falseValue falseValue falseValue)}} YES {{/if}}                                // renders nothing
myValue = 'white'
{{#if (or myValue 'black')}} YES {{else}} NO {{/if}}                                     // renders "YES", the evaluation of both the variable and the string is true

Combined usage:
{{#if (or (equals 'black' 'white') (equals 'white' 'white'))}} YES {{else}} NO {{/if}}   // renders "YES", false OR true evaluates to true
----
|
0.1.0 |

not |
Logical NOT operator. Negates the given parameter; renders if the evaluation is true, otherwise does not render. |
[source,bash]
----
{{#if (not falseValue)}} YES {{else}} NO {{/if}}                // YES
{{#if (not existingValue)}} YES {{else}} NO {{/if}}             // NO
{{#if (not (equals 'black' 'white'))}} YES {{else}} NO {{/if}}  // YES
----
|
0.1.0 |

in |
Checks if the first parameter matches any of the subsequent elements

. |
[source,bash]
----
myValue = 'white'
{{#if (in myValue 'black' 'gray')}} YES {{else}} NO {{/if}}           // NO
{{#if (in myValue 'black' 'white' 'gray')}} YES {{else}} NO {{/if}}   // YES
----
|
0.1.0 |

math |
Helper for basic mathematical operations. The first parameter is the operator, and the other two parameters are the operands. The list of usable operators:

“+”, “-”, “*”, “/”, “%”

If an invalid operator is used, the evaluation result is: “-1”. Otherwise, the result of the mathematical operation on the operands corresponding to the operator. |
[source,bash]
----
num1 = 5
num2 = 8
num3 = 100
num4 = 20

{{math '+' num1 num2}}  // 13
{{math '-' num3 53}}    // 47
{{math '*' num2 num4}}  // 160
{{math '/' num3 num4}}  // 5
{{math '%' num4 num2}}  // 40
{{math 'A' num1 num2}}  // -1
----
|
0.1.0 |
|===

=== Additional Helper Functions

The following 3rd party helper functions can be used in the project:

* https://github.com/jknack/handlebars.java/blob/v4.3.1/handlebars/src/main/java/com/github/jknack/handlebars/helper/StringHelpers.java[StringHelpers]
