name: docker-deploy-after-release

on:
  # the 1st condition
  workflow_run:
    workflows: [ "manual-main-RELEASE","manual-branch-RELEASE" ]
    types:
      - completed
# TODO - manual fix docker deploy after successfully maven release ?
#  workflow_dispatch:
#    # Inputs the workflow accepts.
#    inputs:
#      comment:
#        # Friendly description to be shown in the UI instead of 'name'
#        description: 'Comment for deploy'
#        # Default value if no value is explicitly provided
#        default: 'Deploy SNAPSHOT from WEB UI'
#        # Input has to be provided for the workflow to run
#        required: true

env:
  PROJECT_NAME: ${GITHUB_REPOSITORY#*/}
  DOCKER_BAKE_PLATFORM: linux/amd64,linux/arm64

jobs:

  docker-build:
    runs-on: ubuntu-latest

    steps:

      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v4

      # Get version from POM_XML_PROJECT_VERSION
      - id: getVersion
        name: getVersion into POM_XML_PROJECT_VERSION variable
        run: |
          PROJECT_VERSION=`echo -e 'setns x=http://maven.apache.org/POM/4.0.0\ncat /x:project/x:version/text()' | xmllint --shell pom.xml | grep -v /`
          echo "PROJECT_VERSION=${PROJECT_VERSION}" >> $GITHUB_OUTPUT

      # Set RELEASED_VERSION
      - id: prepare
        name: Set RELEASED_VERSION into etc/release/.env
        run: |
          echo "RELEASED_VERSION="${{steps.getVersion.outputs.PROJECT_VERSION}} >> etc/release/.env

      # https://github.com/docker/docker/login-action
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3

      # https://github.com/docker/bake-action
      - name: docker buildx bake services
        uses: docker/bake-action@v4
        with:
          set: |
            *.platform=${{ env.DOCKER_BAKE_PLATFORM }}
          push: true
          files: |
            etc/release/docker-compose.yml
          targets: qs-rest-service-release
