# This workflow will generate html documentation from asciidoc and publish it to `gh-pages` branch
name: Deploy documentation
on:
  push:
    branches:
      - main
      - bugfix/139-doc-problems # temp test

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch [main]
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'
          cache: 'maven'

      - name: Compile with Maven
        run: mvn -B compile --file pom.xml

      - name: Copy generated docs
        run: |
          mkdir -p docs/modules/ROOT/attachments/generated/openapi
          mv dookug-document/dookug-document-service/target/openapi docs/modules/ROOT/attachments/generated/openapi/dookug-document-service
          mv dookug-api/dookug-api-common/target/config_keys.adoc docs/modules/ROOT/attachments/generated/dookug-api-common-config.adoc
          mv dookug-common/dookug-common-pdfsignature/target/config_keys.adoc docs/modules/ROOT/attachments/generated/dookug-common-pdfsignature-config.adoc

      - name: set-release-version
        id: vars
        run: |
          sudo apt-get update && sudo apt-get install -y libxml2-utils
          POM_XML_PROJECT_VERSION=`echo -e 'setns x=http://maven.apache.org/POM/4.0.0\ncat /x:project/x:version/text()' | xmllint --shell pom.xml | grep -v /`
          echo "POM_XML_PROJECT_VERSION=$POM_XML_PROJECT_VERSION" >> $GITHUB_OUTPUT
          echo CURRENT_VERSION=${POM_XML_PROJECT_VERSION} 
      # Includes the AsciiDoctor GitHub Pages Action to convert adoc files to html and publish to gh-pages branch
      - name: Generate with asciidoctor image
        uses: manoelcampos/asciidoctor-ghpages-action@v2
        with:
          pdf_build: true
          asciidoctor_params: --attribute release_version=${{steps.vars.outputs.POM_XML_PROJECT_VERSION}} --attribute=generatedDoc
          # adoc_file_ext: .ascii # default is .adoc
          source_dir: docs/modules/ROOT # default is .
          ebook_main_adoc_file: index
          # slides_build: true
          # pre_build:
          # post_build:
