# This is a basic workflow that is manually triggered

# 1. create the release branch
# 2. tag the current released version
# 3. deploy released artifact to the maven repository
# 4. bump version + add merge request on main

name: manual-maven-release

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.
    inputs:
      comment:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Comment for release'
        # Default value if no value is explicitly provided
        default: 'Start release from WEB UI'
        # Input has to be provided for the workflow to run
        required: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  release:
    runs-on: ubuntu-latest
    # Permission check https://github.community/t/who-has-permission-to-workflow-dispatch/133981
    if: contains('["rombow","czenczl","petrenyi-mark","speter555","bucherarnold","mate-biro","cserhatit","jhamrak"]', github.actor)

    steps:
      #import gpg key with passphrase
      #- name: Import GPG key
      #  uses: crazy-max/ghaction-import-gpg@v6
      #  with:
      #    gpg_private_key: ${{ secrets.GPG_SIGNING_KEY_GITHUB_TECHUSER }}
      #    passphrase: ${{ secrets.GPG_SIGNING_KEY_PASSPHRASE }}
      - name: Release
        uses: speter555/gh-action-mvn-release-main@v0.32.0
        with:
          GITHUB_TOKEN: '${{ secrets.GH_TOKEN_TECHUSER_JAVA }}'
          ARTIFACT_STORE_SERVER_ID: 'ossrh'
          SETTINGS_XML_PATH: '.github/.m2/settings.xml'
          GPG_KEY_ID_GITHUB_TECHUSER: '${{ secrets.GPG_KEY_ID_GITHUB_TECHUSER }}'
          GPG_SIGNING_KEY_GITHUB_TECHUSER: '${{ secrets.GPG_SIGNING_KEY_GITHUB_TECHUSER }}'
          SSH_PRIVATE_KEY_GITHUB_TECHUSER: '${{ secrets.SSH_PRIVATE_KEY_GITHUB_TECHUSER }}'
          TECH_USER_USERNAME: 'icellmobilsoft-robot'
          TECH_USER_EMAIL: 'github_techuser@icellmobilsoft.hu'
          NEXUS_USER: '${{ secrets.OSS_SONATYPE_ORG_USER }}'
          NEXUS_PASSWORD: '${{ secrets.OSS_SONATYPE_ORG_PASSWORD }}'
          JAVA_VERSION: '17'
          JAVA_DISTRIBUTION: 'temurin'
